name: Pages
on:
  push:
    branches:
      - source

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
